import * as cdk from "aws-cdk-lib";
import * as events from "aws-cdk-lib/aws-events";
import * as targets from "aws-cdk-lib/aws-events-targets";
import * as ecs from "aws-cdk-lib/aws-ecs";
import * as ec2 from "aws-cdk-lib/aws-ec2";
import * as iam from "aws-cdk-lib/aws-iam";
import * as s3 from "aws-cdk-lib/aws-s3";
import { Construct } from "constructs";

export interface TriggerProps {
  env: string;
  inboundBucket: s3.IBucket;
  cluster: ecs.ICluster;
  taskDefinition: ecs.FargateTaskDefinition;
  taskSecurityGroup: ec2.ISecurityGroup;
  subnetIds: string[];
  taskRole: iam.IRole;
  executionRole: iam.IRole;
}

/**
 * TriggerConstruct — S3 ObjectCreated → EventBridge → ECS RunTask (ADR-006b).
 *
 * Wires the file-arrival trigger path:
 *   inbound-raw S3 ObjectCreated event
 *     → EventBridge rule (pattern: source=aws.s3, detail-type=Object Created)
 *     → ECS RunTask via input transformer
 *
 * Input transformer extracts from the S3 event:
 *   S3_BUCKET      → detail.bucket.name
 *   S3_KEY         → detail.object.key
 *   CORRELATION_ID → generated by the task at runtime from S3_KEY prefix
 *   FILE_TYPE      → inferred from S3_KEY suffix (SRG310/SRG315/SRG320)
 *   TENANT_ID      → extracted from S3_KEY path prefix (e.g. "clients/TENANT/file.pgp")
 *
 * Note: CORRELATION_ID is NOT injected by EventBridge — the task generates it
 * deterministically from the S3 key (sha256 prefix) so replays produce the same ID.
 * FILE_TYPE and TENANT_ID parsing are also done inside the task from S3_KEY.
 *
 * The EventBridge rule scopes to the inbound-raw bucket by bucket name.
 * Requires eventBridgeEnabled: true on inbound-raw (already set in StorageConstruct).
 *
 * Separate trigger path from the nightly delivery gate (ADR-007 / SchedulerConstruct).
 */
export class TriggerConstruct extends Construct {
  public readonly triggerRole: iam.Role;

  constructor(scope: Construct, id: string, props: TriggerProps) {
    super(scope, id);

    // IAM role for EventBridge to invoke ECS RunTask
    this.triggerRole = new iam.Role(this, "TriggerRole", {
      roleName: `onefintech-${props.env}-s3-trigger-role`,
      assumedBy: new iam.ServicePrincipal("events.amazonaws.com"),
      description: "EventBridge → ECS RunTask for S3 file-arrival trigger (ADR-006b)",
    });
    this.triggerRole.addToPolicy(new iam.PolicyStatement({
      sid: "AllowEcsRunTask",
      actions: ["ecs:RunTask"],
      resources: [props.taskDefinition.taskDefinitionArn],
    }));
    this.triggerRole.addToPolicy(new iam.PolicyStatement({
      sid: "AllowPassTaskRole",
      actions: ["iam:PassRole"],
      resources: [
        props.taskRole.roleArn,
        props.executionRole.roleArn,
      ],
      conditions: {
        StringLike: { "iam:PassedToService": "ecs-tasks.amazonaws.com" },
      },
    }));

    // EventBridge rule: S3 ObjectCreated on inbound-raw bucket
    const rule = new events.Rule(this, "S3InboundTriggerRule", {
      ruleName: `onefintech-${props.env}-s3-inbound-trigger`,
      description: "S3 ObjectCreated on inbound-raw → ECS ingest-task (ADR-006b)",
      eventPattern: {
        source: ["aws.s3"],
        detailType: ["Object Created"],
        detail: {
          bucket: {
            name: [props.inboundBucket.bucketName],
          },
          // Scope to .pgp files only — ignore lifecycle, access log objects, etc.
          object: {
            key: [{ suffix: ".pgp" }],
          },
        },
      },
    });

    // ECS RunTask target with container environment overrides
    // S3_BUCKET and S3_KEY are injected from the EventBridge event via input transformer.
    // All other config comes from the task definition's static environment block.
    rule.addTarget(
      new targets.EcsTask({
        cluster: props.cluster,
        taskDefinition: props.taskDefinition,
        launchType: ecs.LaunchType.FARGATE,
        role: this.triggerRole,
        securityGroups: [props.taskSecurityGroup],
        subnetSelection: {
          subnets: props.subnetIds.map((id) =>
            ec2.Subnet.fromSubnetId(scope, `TriggerSubnet-${id}`, id)
          ),
        },
        containerOverrides: [
          {
            containerName: "ingest-task",
            environment: [
              {
                name: "S3_BUCKET",
                value: events.EventField.fromPath("$.detail.bucket.name"),
              },
              {
                name: "S3_KEY",
                value: events.EventField.fromPath("$.detail.object.key"),
              },
            ],
          },
        ],
      })
    );

    cdk.Tags.of(this).add("Project", "OneFintechFIS");
    cdk.Tags.of(this).add("Environment", props.env);
  }
}
