// Package ports defines the domain-facing contracts for the Card and Member API.
// Callers speak One Fintech language only — no FIS identifiers appear here.
package ports

import (
	"context"
	"errors"
	"time"

	"github.com/google/uuid"
)

// ─── Sentinel errors ─────────────────────────────────────────────────────────

var (
	ErrMemberNotFound    = errors.New("member not found")
	ErrCardNotFound      = errors.New("card not found")
	ErrMemberNotResolved = errors.New("member FIS identifiers not yet assigned — batch return file pending")
	ErrAlreadyCancelled  = errors.New("card already cancelled")
	ErrDuplicateRequest  = errors.New("duplicate request — idempotency key already accepted")
	ErrInvalidRequest    = errors.New("invalid request")
)

// ─── Caller context ───────────────────────────────────────────────────────────

type CallerType string

const (
	CallerUniversalWallet  CallerType = "universal_wallet"
	CallerIVR              CallerType = "ivr"
	CallerBatchPipeline    CallerType = "batch_pipeline"
	CallerDeadLetterRepair CallerType = "dead_letter_repair"
	CallerOpsPortal        CallerType = "ops_portal"
)

// RequestContext is populated by middleware and passed on every service call.
//
// CorrelationID and IdempotencyKey serve different purposes and must not be conflated:
//
//   CorrelationID  — a per-request trace identifier. Changes on every HTTP call.
//                   Used in logs, audit entries, and observability events so a
//                   single request can be traced end-to-end. Never used as a
//                   deduplication key.
//
//   IdempotencyKey — a caller-supplied operation identifier, stable across retries
//                   of the same logical operation. Used exclusively by the
//                   domain_commands idempotency gate. If a caller retries a
//                   CancelCard request after a timeout, they send the same
//                   IdempotencyKey so the gate recognises the duplicate and
//                   returns the cached result without re-executing at FIS.
//                   For dead letter repair this is the original batch correlation UUID.
type RequestContext struct {
	// CorrelationID is the per-request trace ID, sourced from X-Correlation-ID.
	// Generated by middleware if the caller omits it.
	// Used in logs and audit entries only — never for deduplication.
	CorrelationID uuid.UUID

	// IdempotencyKey is the caller-supplied operation dedup key, sourced from X-Idempotency-Key.
	// Must be supplied by the caller and held stable across retries of the same operation.
	// Feeds the domain_commands gate. Required on all mutating operations.
	// For dead letter repair: pass the original batch correlation UUID.
	IdempotencyKey uuid.UUID

	TenantID        string
	CallerType      CallerType
	SubjectMemberID *uuid.UUID // non-nil for UW member-authenticated requests
}

// ─── Card service ─────────────────────────────────────────────────────────────

type CancelReason string

const (
	CancelReasonLost          CancelReason = "LOST"
	CancelReasonStolen        CancelReason = "STOLEN"
	CancelReasonMemberRequest CancelReason = "MEMBER_REQUEST"
	CancelReasonProgramEnd    CancelReason = "PROGRAM_END"
	CancelReasonFraud         CancelReason = "FRAUD"
	CancelReasonOpsOverride   CancelReason = "OPS_OVERRIDE"
)

type CancelCardRequest struct {
	Rctx         RequestContext
	MemberID     *uuid.UUID
	CardToken    *string
	CancelReason CancelReason
}

type CancelCardResult struct {
	CardID       uuid.UUID
	MemberID     uuid.UUID
	CancelledAt  time.Time
	PursesClosed int
}

type ReplaceReason string

const (
	ReplaceReasonLost        ReplaceReason = "LOST"
	ReplaceReasonCompromised ReplaceReason = "COMPROMISED"
	ReplaceReasonRenewal     ReplaceReason = "RENEWAL"
	ReplaceReasonBINChange   ReplaceReason = "BIN_CHANGE"
)

type ReplaceCardRequest struct {
	Rctx     RequestContext
	MemberID uuid.UUID
	Reason   ReplaceReason
}

type ReplaceCardResult struct {
	OldCardID  uuid.UUID
	NewCardID  uuid.UUID
	MemberID   uuid.UUID
	ReplacedAt time.Time
}

type LoadFundsRequest struct {
	Rctx          RequestContext
	MemberID      uuid.UUID
	BenefitType   string
	AmountCents   int64
	BenefitPeriod string
}

type LoadFundsResult struct {
	CardID      uuid.UUID
	PurseID     uuid.UUID
	AmountCents int64
	LoadedAt    time.Time
}

type GetBalanceRequest struct {
	Rctx     RequestContext
	MemberID uuid.UUID
}

type PurseBalance struct {
	BenefitType    string
	PurseName      string
	AvailableCents int64
	SettledCents   int64
	Status         string
}

type GetBalanceResult struct {
	MemberID uuid.UUID
	CardID   uuid.UUID
	Purses   []PurseBalance
	AsOf     time.Time
}

type ResolveCardRequest struct {
	Rctx  RequestContext
	Token string
}

type ResolveCardResult struct {
	MemberID uuid.UUID
	CardID   uuid.UUID
	Status   string
}

// ICardService is the domain service for card lifecycle operations.
// All mutating methods are idempotent on the same IdempotencyKey.
type ICardService interface {
	CancelCard(ctx context.Context, req CancelCardRequest) (*CancelCardResult, error)
	ReplaceCard(ctx context.Context, req ReplaceCardRequest) (*ReplaceCardResult, error)
	LoadFunds(ctx context.Context, req LoadFundsRequest) (*LoadFundsResult, error)
	GetBalance(ctx context.Context, req GetBalanceRequest) (*GetBalanceResult, error)
	ResolveCard(ctx context.Context, req ResolveCardRequest) (*ResolveCardResult, error)
}

// ─── Member service ───────────────────────────────────────────────────────────

type EnrollMemberRequest struct {
	Rctx           RequestContext
	ClientMemberID string
	SubprogramID   int64
	BenefitPeriod  string
	FirstName      string
	LastName       string
	DOB            time.Time
	Address1       string
	Address2       string
	City           string
	State          string
	ZIP            string
	Phone          string
	Email          string
	CardDesignID   string
}

type EnrollMemberResult struct {
	MemberID    uuid.UUID
	CardID      uuid.UUID
	FISResolved bool
	CreatedAt   time.Time
}

type UpdateMemberRequest struct {
	Rctx      RequestContext
	MemberID  uuid.UUID
	FirstName string
	LastName  string
	DOB       time.Time
	Address1  string
	Address2  string
	City      string
	State     string
	ZIP       string
	Phone     string
	Email     string
}

type MemberView struct {
	MemberID       uuid.UUID
	ClientMemberID string
	Status         string
	FISResolved    bool
	CardID         *uuid.UUID
	CardStatus     *string
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

// IMemberService is the domain service for member lifecycle operations.
// All mutating methods are idempotent on the same IdempotencyKey.
type IMemberService interface {
	EnrollMember(ctx context.Context, req EnrollMemberRequest) (*EnrollMemberResult, error)
	UpdateMember(ctx context.Context, req UpdateMemberRequest) error
	GetMember(ctx context.Context, rctx RequestContext, memberID uuid.UUID) (*MemberView, error)
}
