// Package ports defines the domain-facing request/response types and service
// interfaces for the Card and Member API.
//
// Callers (Universal Wallet, IVR, batch pipeline, dead letter repair) speak
// entirely in One Fintech ubiquitous language. No FIS identifiers, no FIS
// status codes, no purse numbers appear at this boundary.
//
// PHI fields are annotated. The Zero-PHI log contract from §7.2 applies:
// IDs in this layer are UUIDs or opaque string references — never names,
// DOBs, addresses, or card numbers.
package ports

import (
	"context"
	"errors"
	"time"

	"github.com/google/uuid"
)

// ─── Sentinel errors ─────────────────────────────────────────────────────────

var (
	// ErrMemberNotFound is returned when no consumer row exists for the given ID.
	ErrMemberNotFound = errors.New("card_member_api: member not found")

	// ErrCardNotFound is returned when no card row exists for the given member.
	ErrCardNotFound = errors.New("card_member_api: card not found")

	// ErrMemberNotResolved is returned when a real-time card operation is attempted
	// on a member whose FisPersonID or FisCardID has not yet been assigned by FIS.
	// This can happen if the batch return file has not yet been processed (Stage 7).
	ErrMemberNotResolved = errors.New("card_member_api: member FIS identifiers not yet resolved — batch return file pending")

	// ErrAlreadyCancelled is returned when CancelCard is called on a card already
	// in CardClosed state. Surfaces as idempotent success to the caller
	// (the desired state is already achieved) but is logged for audit.
	ErrAlreadyCancelled = errors.New("card_member_api: card already cancelled")

	// ErrDuplicateRequest is returned when the idempotency gate detects a
	// domain_commands row with Accepted or Completed status for the same key.
	ErrDuplicateRequest = errors.New("card_member_api: duplicate request — idempotency key already accepted")
)

// ─── Caller context ───────────────────────────────────────────────────────────

// CallerType identifies the surface that originated a request.
// Used for audit log entries and observability dimensions — not for authz logic.
// Authorization is enforced by the JWT claims middleware before the handler runs.
type CallerType string

const (
	CallerUniversalWallet CallerType = "universal_wallet"
	CallerIVR             CallerType = "ivr"
	CallerBatchPipeline   CallerType = "batch_pipeline"
	CallerDeadLetterRepair CallerType = "dead_letter_repair"
	CallerOpsPortal       CallerType = "ops_portal"
)

// RequestContext carries the cross-cutting identity fields present on every
// inbound request. Populated by middleware before the handler is invoked.
type RequestContext struct {
	// CorrelationID is the idempotency key. For dead letter repair this is the
	// same UUID that was on the original batch record — same key, same gate.
	// For IVR and UW requests this is generated by the caller and must be a v4 UUID.
	CorrelationID uuid.UUID

	TenantID  string
	CallerType CallerType

	// SubjectMemberID is the authenticated member UUID from the JWT sub claim.
	// Present for UW requests only — nil for IVR and service-to-service calls.
	SubjectMemberID *uuid.UUID
}

// ─── Cancel Card ─────────────────────────────────────────────────────────────

// CancelCardRequest is the domain-level request to cancel a member's card.
//
// Callers identify the card by one of:
//   - MemberID (UW, batch repair — UUID from One Fintech consumers table)
//   - CardToken (IVR — opaque token from physical card swipe; resolved via FIS translate)
//
// Exactly one of MemberID or CardToken must be non-nil. The service validates this.
//
// CancelReason determines how the cancel is recorded in audit_log and
// passed to FIS as the close reason code.
type CancelCardRequest struct {
	Rctx RequestContext

	// MemberID — One Fintech UUID. Use when caller has authenticated member context.
	// Mutually exclusive with CardToken.
	MemberID *uuid.UUID

	// CardToken — physical card token or proxy from IVR card swipe.
	// Mutually exclusive with MemberID.
	// Resolved to FisCardID via TranslateCardNumber before any domain lookup.
	CardToken *string

	CancelReason CancelReason
}

// CancelReason is the semantic reason for card cancellation.
type CancelReason string

const (
	CancelReasonLost        CancelReason = "LOST"
	CancelReasonStolen      CancelReason = "STOLEN"
	CancelReasonMemberRequest CancelReason = "MEMBER_REQUEST"
	CancelReasonProgramEnd  CancelReason = "PROGRAM_END"
	CancelReasonFraud       CancelReason = "FRAUD"
	CancelReasonOpsOverride CancelReason = "OPS_OVERRIDE"
)

// CancelCardResult is returned on success.
// CardID is the One Fintech UUID — not the FIS cardId.
type CancelCardResult struct {
	CardID      uuid.UUID
	MemberID    uuid.UUID
	CancelledAt time.Time
	// PursesClosed is the count of purse slots that were explicitly closed at FIS.
	// For RFU this will be 2 (F&V + Pantry).
	PursesClosed int
}

// ─── Member Enroll ────────────────────────────────────────────────────────────

// EnrollMemberRequest is the domain-level request to enroll a new member.
// This is the net-new REST enrollment path — equivalent to a single SRG310 row
// arriving via the batch pipeline, processed through the same validation and
// idempotency gate.
//
// Validation rules (same as Stage 2 batch validation):
//   - ClientMemberID must be unique within TenantID
//   - BenefitPeriod must be current or future ISO YYYY-MM
//   - SubprogramID must resolve to a known program in the programs table
type EnrollMemberRequest struct {
	Rctx RequestContext

	ClientMemberID string // PHI — health plan member ID; natural key
	SubprogramID   int64  // FIS subprogram e.g. 26071 for RFU Oregon
	BenefitPeriod  string // ISO YYYY-MM

	// Demographics — PHI
	FirstName string
	LastName  string
	DOB       time.Time
	Address1  string
	Address2  string
	City      string
	State     string // 2-char
	ZIP       string
	Phone     string
	Email     string

	// Optional card customisation
	CardDesignID string
	CustomCardID string
}

// EnrollMemberResult is returned on successful enrollment.
type EnrollMemberResult struct {
	MemberID  uuid.UUID
	CardID    uuid.UUID
	CreatedAt time.Time
	// FISResolved indicates whether FIS identifiers were assigned synchronously.
	// For the REST enrollment path this will be true if Code Connect is available.
	// For batch-originated enrollment this is false until Stage 7 return file.
	FISResolved bool
}

// ─── Update Demographics ──────────────────────────────────────────────────────

// UpdateMemberRequest maps to PUT /members/{id}.
// All fields are optional — zero values are omitted from the FIS PUT call.
type UpdateMemberRequest struct {
	Rctx     RequestContext
	MemberID uuid.UUID

	// PHI — only populated fields are updated
	FirstName string
	LastName  string
	DOB       time.Time
	Address1  string
	Address2  string
	City      string
	State     string
	ZIP       string
	Phone     string
	Email     string
}

// ─── Replace Card ─────────────────────────────────────────────────────────────

// ReplaceCardRequest maps to POST /cards/{id}/replace.
// Produces a new FisCardID — Aurora is updated atomically inside the service.
type ReplaceCardRequest struct {
	Rctx      RequestContext
	MemberID  uuid.UUID
	Reason    ReplaceReason
}

// ReplaceReason is the semantic reason for card replacement.
type ReplaceReason string

const (
	ReplaceReasonLost        ReplaceReason = "LOST"
	ReplaceReasonCompromised ReplaceReason = "COMPROMISED"
	ReplaceReasonRenewal     ReplaceReason = "RENEWAL"
	ReplaceReasonBINChange   ReplaceReason = "BIN_CHANGE"
)

// ReplaceCardResult is returned on success.
type ReplaceCardResult struct {
	OldCardID   uuid.UUID
	NewCardID   uuid.UUID
	MemberID    uuid.UUID
	ReplacedAt  time.Time
}

// ─── Load Funds ───────────────────────────────────────────────────────────────

// LoadFundsRequest maps to POST /cards/{id}/load.
// Used by dead letter repair for failed RT60 records and manual ops loads.
// BenefitType routes to the correct FIS purse number — callers never specify purseNumber.
type LoadFundsRequest struct {
	Rctx        RequestContext
	MemberID    uuid.UUID
	BenefitType string // "OTC" or "FOD" — routes to correct FisPurseNumber
	AmountCents int64
	BenefitPeriod string // ISO YYYY-MM — used for idempotency key scoping
}

// LoadFundsResult is returned on success.
type LoadFundsResult struct {
	CardID        uuid.UUID
	PurseID       uuid.UUID
	AmountCents   int64
	LoadedAt      time.Time
}

// ─── Balance Read ─────────────────────────────────────────────────────────────

// GetBalanceRequest maps to GET /cards/{id}/balance.
// Always reads live from FIS — never served from Aurora sub-ledger.
type GetBalanceRequest struct {
	Rctx     RequestContext
	MemberID uuid.UUID
}

// PurseBalance is one purse slot in the balance response.
type PurseBalance struct {
	BenefitType     string // "OTC" or "FOD"
	PurseName       string // e.g. "OTC2550"
	AvailableCents  int64
	LedgerCents     int64
	Status          string
}

// GetBalanceResult contains all purse balances for a member's card.
type GetBalanceResult struct {
	MemberID   uuid.UUID
	CardID     uuid.UUID
	Purses     []PurseBalance
	AsOf       time.Time // time of FIS response
}

// ─── Resolve token → member ───────────────────────────────────────────────────

// ResolveCardRequest maps to POST /cards/resolve.
// Accepts a card token or proxy and returns the One Fintech member context.
// Used by IVR to identify a member from a card swipe before cancel/balance ops.
type ResolveCardRequest struct {
	Rctx  RequestContext
	Token string // card number token or proxy number
}

// ResolveCardResult is the One Fintech member context for a resolved token.
type ResolveCardResult struct {
	MemberID uuid.UUID
	CardID   uuid.UUID
	Status   string
}

// ─── Service interfaces ────────────────────────────────────────────────────────

// ICardService is the domain service interface for card lifecycle operations.
// Handlers call this — not the FIS port directly.
// The service owns: idempotency gate, FIS ID resolution, Aurora writes, audit log.
type ICardService interface {
	// CancelCard closes the card and all purse slots at FIS, then updates Aurora.
	// Idempotent: returns ErrAlreadyCancelled (not an error to the caller) if card
	// is already in CardClosed state.
	CancelCard(ctx context.Context, req CancelCardRequest) (*CancelCardResult, error)

	// ReplaceCard replaces the physical card at FIS and atomically updates cardId in Aurora.
	ReplaceCard(ctx context.Context, req ReplaceCardRequest) (*ReplaceCardResult, error)

	// LoadFunds loads benefit funds to the correct purse slot, routed by BenefitType.
	// Used for dead letter repair of failed RT60 records.
	LoadFunds(ctx context.Context, req LoadFundsRequest) (*LoadFundsResult, error)

	// GetBalance reads live purse balances from FIS. Never serves from Aurora sub-ledger.
	GetBalance(ctx context.Context, req GetBalanceRequest) (*GetBalanceResult, error)

	// ResolveCard translates a card token/proxy to One Fintech member context.
	// Entry point for IVR flows before cancel or balance operations.
	ResolveCard(ctx context.Context, req ResolveCardRequest) (*ResolveCardResult, error)
}

// IMemberService is the domain service interface for member lifecycle operations.
type IMemberService interface {
	// EnrollMember creates a new member at FIS and in Aurora.
	// Equivalent to a single SRG310 row through the same validation and idempotency gate.
	EnrollMember(ctx context.Context, req EnrollMemberRequest) (*EnrollMemberResult, error)

	// UpdateMember updates member demographics at FIS and in Aurora.
	UpdateMember(ctx context.Context, req UpdateMemberRequest) error

	// GetMember returns member state from Aurora (not a live FIS call).
	GetMember(ctx context.Context, rctx RequestContext, memberID uuid.UUID) (*MemberView, error)
}

// MemberView is the read model returned by GetMember.
// FIS identifiers are omitted — callers never need raw FIS IDs.
type MemberView struct {
	MemberID       uuid.UUID
	ClientMemberID string // PHI
	Status         string
	FISResolved    bool       // true when personId + cardId assigned
	CardID         *uuid.UUID // nil until card issued
	CardStatus     *string
	CreatedAt      time.Time
	UpdatedAt      time.Time
}
